name: crypto_currency
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  dio: ^5.0.2
  flutter_driver:
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
