name: crypto_currency
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_driver:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  logger: ^2.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_screen/
    - assets/images/

  fonts:
    - family: 'SF Pro Display'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400

    - family: 'SF Pro Text'
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
