name: Test, build and deploy app
on: [push, pull_request]
jobs:
  build_deploy:
    if: github.event_name != 'pull_request'
    runs-on: macos-latest
    needs: [drive_ios, drive_android, test]
    name: Build  apk  and web
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: flutter  config --enable-web
      - run: flutter  config --enable-linux-desktop
      - run: flutter  config --enable-macos-desktop
      - run: flutter  config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build macos --release
      - run: flutter build apk --debug --split-per-abi

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/apk/debug/*.apk,build/macos/Build/Products/Release/*.app'
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: flutter build web

      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/web
