name: Test, build and deploy app

on: [push, pull_request]

jobs:
  test:
    name: 'Test before build and deploy'
    runs-on: unubtu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup java-version
        uses: actions/setup-java@v2
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Run tests
        run: flutter test

  build_anroid:
    name: Build and Deploy Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Deploy APK to GitHub Releases
        uses: ncipollo/release-action@v2
        with:
          artifacts: |
            build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
        if: success()

  build_ios:
    name: Build and Deploy iOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Deploy iOS to GitHub Releases
        uses: ncipollo/release-action@v2
        with:
          artifacts: |
            build/ios/iphoneos/Runner.app
          token: ${{ secrets.GITHUB_TOKEN }}
        if: success()

  build_web:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Deploy web to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/web
        if: success()
