name: Test, build and deploy IOS
on: [push, pull_request]
jobs:
  drive_ios:
    strategy:
      matrix:
        device:
          - 'iPhone 8 (13.1)'
          - 'iPhone 11 Pro Max (13.1)'
      fail-fast: false
    runs-on: macos-latest
    needs: test
    steps:
      - name: List all simulators
        run: xcrun instruments -s
      - name: Start Simulator
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=${{ matrix.device }}' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run Flutter Driver tests
        run: flutter drive --driver=test_driver/app.dart --target=test_driver/app_test.dart
